### ISSUE TITLE
Error in depth estimation data preparation

### ISSUE THREAD

**Issue by Yijia-Xiao** [autonomousvision/unimatch#4]
Hi,

Thanks for the great work!
I am trying to finetune the depth estimation model on some other datasets. But I encountered errors preparing the downloaded datasets when I tried to train on the depth dataset you provided. Below are error information.
Thank you!

```
$ python prepare_demon_train.py 
Converting rgbd_bugfix_10_to_20_3d_train.h5 ...
Processing sequence 0/1237
prepare_demon_train.py:67: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img = imageio.imread(img.tobytes())
Traceback (most recent call last):
  File "prepare_demon_train.py", line 119, in <module>
    preparedata()
  File "prepare_demon_train.py", line 96, in preparedata
    dump_example(scene)
  File "prepare_demon_train.py", line 67, in dump_example
    img = imageio.imread(img.tobytes())
  File ".../lib/python3.8/site-packages/imageio/__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File ".../lib/python3.8/site-packages/imageio/v2.py", line 226, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File ".../lib/python3.8/site-packages/imageio/core/imopen.py", line 303, in imopen
    raise err_type(err_msg)
ValueError: Could not find a backend to open `<bytes>`` with iomode `ri`.
```

**Comment by haofeixu** [comment]
Hi, thanks for reporting this issue.

You issue seems to be the version issue of imageio, you can downgrade imageio to 2.9.0 with `pip install imageio=2.9.0`.

BTW, I just updated the depth data downloading script, where a small issue is fixed. Please re-download the depth data using the latest commit, sorry for the inconvenience.

**Comment by Yijia-Xiao** [comment]
Hi @haofeixu,

Thank you for your reply. I will try it out.

**Comment by Yijia-Xiao** [comment]
Hi @haofeixu ,

Problem solved. Thank you!
